framework:
    mailer:
        dsn: 'smtp://%env(MAILER_USER)%:%env(resolve:MAILER_PASS)%@%env(MAILER_HOST)%?encryption=tls&auth_mode=plain'
        envelope:
            sender: 'noreply@blizzfull.fr'
