---
- hosts: server
  become: yes

  vars_files:
    - vars.yml
    - secrets.yml
  tasks:
  - name: Install nginx
    ansible.builtin.apt:
      name: nginx
      state: present
  # Enable template Conf
  - name: Copy nginx configuration
    template: src=default.conf dest=/etc/nginx/conf.d/default.conf

  - name: Start nginx Service
    ansible.builtin.service:
      name: nginx
      state: restarted
      enabled: yes