---
- hosts: server
  become: yes

  vars_files:
    - vars.yml
    - secrets.yml
  tasks:
   # Install php and extensions
  - name: Install php-fpm
    ansible.builtin.apt:
      pkg:
        - php
        - php-fpm
        - php-enchant
        - php-mbstring
        - php-mysql
        - php-xml